osx_image: xcode8.3
language: objective-c
before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir

xcode_project: ShareBudget.xcodeproj # path to your xcodeproj folder
xcode_scheme: ShareBudgetTests

after_success:
  - bash <(curl -s https://codecov.io/bash)  -J 'ShareBudget'
