osx_image: xcode8.3
language: objective-c
xcode_project: ShareBudget.xcodeproj # path to your xcodeproj folder
xcode_scheme: ShareBudgetTests

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

after_success:
  - bash <(curl -s https://codecov.io/bash)  -J 'ShareBudget'


