language: python
python:
  - "2.7"
before_script:
  - psql -c 'create database postgres_test;' -U postgres
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest