osx_image: xcode8.3
language: objective-c
xcode_project: ShareBudget.xcodeproj # path to your xcodeproj folder
xcode_scheme: ShareBudgetTests

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace ShareBudget.xcworkspace -scheme ShareBudgetTests CODE_SIGNING_REQUIRED=NO GCC_GENERATE_TEST_COVERAGE_FILES=YES -enableCodeCoverage YES

after_success:
  - bash <(curl -s https://codecov.io/bash)  -J 'ShareBudget'


